'use strict'
const order = require('../controllers/order')
const express = require('express')
const router = express.Router()

router.post('/', order.create)
router.put('/stock', order.setStockPrinted)
router.get('/orders', order.findOrders)
router.get('/items', order.findItems)
router.get('/stock', order.getStockToPrint)
router.put('/items/:id', order.updateItemStatus)
router.get('/order_items', order.findOrderItems)
router.get('/order_turns', order.findOrderTurns)
router.get('/:id', order.findById)
router.get('/', order.findAll)
router.put('/printed/:id', order.setOrderPrinted)
router.put('/:id', order.updateOrderStatus)
router.delete('/destroy', order.destroyOrders)
router.delete('/:id', order.delete)
module.exports = router
