const types = {
  LOAD_CATEGORIES: "CATEGORIES/LOAD",
  SET_CATEGORIES: "CATEGORIES/SET",

  LOAD_PRODUCTS: "PRODUCTS/LOAD",
  SET_PRODUCTS: "PRODUCTS/SET",
  FILTER_BY_CATEGORY: "PRODUCTS/FILTER_BY_CATEGORY",
  SET_CATEGORY_ID: "CATEGORY_ID/SET",

  LOAD_BASKET: "BASKET/LOAD",
  SET_BASKET: "BASKET/SET",
  RESET_VIEW: "VIEW/RESET",

  ADD_ITEM: "ITEM/ADD",
  SEND_ITEM_TO_BASKET: "ITEM/SEND_TO_BASKET",
  REMOVE_ITEM: "ITEM/REMOVE",
  REMOVE_ITEM_FROM_BASKET: "ITEM/REMOVE_FROM_BASKET",

  SET_ITEM: "ITEM/SET",
  SET_ITEM_FOR_VIEW: "ITEM/SET_FOR_VIEW",
  UNSET_ITEM: "ITEM/UNSET",
  UNSET_ITEM_FROM_VIEW: "ITEM/UNSET_FROM_VIEW",

  CHECK_UPDATES: "UPDATES/CHECK",
  SET_UPDATES: "UPDATES/SET",

  SEND_AKNOWLEDGE: "AKNOWLEDGE/SEND"

};

export { types };
